# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{khronotab}
  s.version = "1.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristofer M White"]
  s.date = %q{2010-07-15}
  s.description = %q{A pure ruby cron parser with a hash-like interface}
  s.email = %q{me@kmwhite.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "demo/sample.ct",
     "demo/sample.rb",
     "khronotab.gemspec",
     "lib/khronotab.rb",
     "lib/khronotab/cron_job.rb",
     "lib/khronotab/cron_unit.rb",
     "lib/khronotab/cron_variable.rb"
  ]
  s.homepage = %q{http://github.com/kmwhite/khronotab}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{khronotab}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A pure ruby cron parser}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

